# Generated by Django 3.1 on 2020-08-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='package',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
