# Generated by Django 3.1 on 2020-08-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_campaign_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='estimates_reach',
            new_name='estimated_reach',
        ),
    ]
