# Generated by Django 3.1 on 2020-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200829_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='estimated_reach',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_budget',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='package',
            field=models.SmallIntegerField(null=True),
        ),
    ]
