# Generated by Django 3.1 on 2020-08-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200830_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='no phone numbe', max_length=15),
        ),
    ]
